// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zvxpwmqnwltjisnqmgzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2eHB3bXFud2x0amlzbnFtZ3pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY3ODE5OTMsImV4cCI6MjA4MjM1Nzk5M30.ijQScVXB-mZgXa-N9Vn7ASAnPRPm12M1y9j41nAUedc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);